# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "perk/ubuntu-20.04-arm64"

  # Provisioning configuration for Ansible
  config.vm.provision"ansible"do|ansible|
    ansible.playbook = "playbook.yml"
  end
end